---
- hosts: all
  tasks:
    - name: 'Find any files from debug'
      find:
        paths: "/tmp/debug-{{ pipeline_type }}-{{ pipeline_version }}-{{ pipeline_os }}"
        recurse: true
        hidden: true
      register: debug_files
    - name: 'Fetch debug files'
      fetch:
        src: "{{ item.path }}"
        dest: "{{ workspace }}"
      with_items: "{{ debug_files.files }}"
      become: true
