---
- hosts: localhost
  tasks:
    - name: 'Get a new node'
      evgeni.duffy.session_request:
        pool: metal-ec2-c5n-centos-8s-x86_64
        quantity: 1
      register: duffy_data

    - name: 'Fail if no hosts returned'
      fail:
        msg: 'Could not get hosts from ci.centos.org'
      when: duffy_data.nodes|length == 0

    - name: 'Write data locally'
      copy:
        content: "{{ duffy_data.session }}"
        dest: "{{ playbook_dir }}/duffy_session"

    - name: 'Write inventory'
      copy:
        content: |
          {% for host in duffy_data.nodes %}
          {{ host['hostname'] }} ansible_fqdn={{ host['hostname'] }} ansible_user=root ansible_host={{ host['ipaddr'] }}
          {% endfor %}
        dest: "{{ playbook_dir }}/duffy_inventory"

    - name: 'Fetch default ssh_config'
      slurp:
        src: /etc/ssh/ssh_config
      register: etc_ssh_config

    - name: 'Write ssh config file'
      template:
        src: templates/ssh_config_duffy.j2
        dest: "{{ playbook_dir }}/ssh_config"
      vars:
        ssh_config_base: "{{ etc_ssh_config['content'] | b64decode }}"
