---
- hosts: localhost
  tasks:
    - name: 'Get a new node'
      evgeni.duffy.session_request:
        pool: metal-ec2-c5n-centos-9s-x86_64
        quantity: 1
      register: duffy_data

    - name: 'Write data locally'
      copy:
        content: "{{ duffy_data.session }}"
        dest: "{{ playbook_dir }}/duffy_session"

    - name: 'Fetch default ssh_config'
      slurp:
        src: /etc/ssh/ssh_config
      register: etc_ssh_config

    - name: 'Write ssh config file'
      template:
        src: templates/ssh_config_duffy.j2
        dest: "{{ playbook_dir }}/ssh_config"
      vars:
        ssh_config_base: "{{ etc_ssh_config['content'] | b64decode }}"
        duffy_hostname: "{{ duffy_data['nodes'][0]['hostname'] }}"
